# Homemaker configuration file
# https://github.com/FooSoft/homemaker
[tasks.default]
  deps = ["fetch_submodules", "atom", "fish", "git"]

[tasks.atom]
  links = [
    [".atom/", "atom/"]
  ]
  cmds = [
    ["apm", "install", "--packages-file", ".atom/packages.lst"]
  ]

[tasks.fish]
  links = [
    [".config/fish/", "fish"]
  ]

[tasks.emacs]
  links = [
    [".emacs.d/", "emacs"]
  ]

[tasks.git]
  links = [
    [".gitconfig",        "git/gitconfig"],
    [".gitignore_global", "git/gitignore_global"]
  ]

[tasks.vim]
  links = [
    [".vimrc", "vimrc"],
  ]

[tasks.fetch_submodules]
  cmds = [
    [ "sh", "-c", "cd $HM_SRC/$GIT_DEST && git submodule update --init --recursive" ]
  ]
