#!/bin/sh
## Idle configuration
exec swayidle -w \
    timeout 600 'swaylock' \
    before-sleep 'swaylock --fade-in 0'
# This will lock your screen after 600 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
