[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xc0c5ce"
duration = 0

[[colors.indexed_colors]]
color = "0xf99157"
index = 16

[[colors.indexed_colors]]
color = "0xab7967"
index = 17

[[colors.indexed_colors]]
color = "0x343d46"
index = 18

[[colors.indexed_colors]]
color = "0x4f5b66"
index = 19

[[colors.indexed_colors]]
color = "0xa7adba"
index = 20

[[colors.indexed_colors]]
color = "0xcdd3de"
index = 21

[colors.bright]
black = "0x65737e"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0x99c794"
magenta = "0xc594c5"
red = "0xec5f67"
white = "0xd8dee9"
yellow = "0xfac863"

[colors.cursor]
cursor = "0xc0c5ce"
text = "0x1b2b34"

[colors.normal]
black = "0x1b2b34"
blue = "0x6699cc"
cyan = "0x5fb3b3"
green = "0x99c794"
magenta = "0xc594c5"
red = "0xec5f67"
white = "0xc0c5ce"
yellow = "0xfac863"

[colors.primary]
background = "0x1b2b34"
foreground = "0xc0c5ce"

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Underline"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Hasklug Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font"
style = "Regular"

[hints]
alphabet = "1234567890"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "X"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 0.70
title = "alacritty"

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 8
y = 8
